name: KitUI
author: Infernus101
main: Infernus101\KitUI\Main
version: 1.3.5
api: [3.0.0, 3.8.3]
commands:
  kit:
    description: KitUI Command
permissions:
 kit.command:
  default: true
 kit.sign:
   default: false
 kit.freepass:
   default: false
